### ISSUE TITLE
登陆进去之后左上角点回welcome会重新自动登录

### ISSUE THREAD

**Issue by guoguo616** [Aahung/cityu-sports#1]
那点回去还有什么意义。。。应该停留在输入EID密码的界面等待点击按钮登陆的吧。。

**Comment by aahung** [comment]
这个点回去的按钮在设计中并没有出现，这个bug我在iOS 7 中重现了，原因是iOS 7 和iOS 8 对同一segue的表现形式不一导致的：
For same "Show Detail" segue, 
- iOS 8 push the page from bottom and replace the log in page, without providing "< Welcome" back button
- iOS 7 push the page from right to left and providing the back button

I change "Show Detail" segue to "Present Modally" segue in order to conform the behaviours in iOS 7 and 8. After version 1.0.2 (24) reviewed by Apple (which may be done within 5 days), I will submit [1.0.3 (25)](https://github.com/Aahung/cityu-sports/commit/d3a714505292a97554e85a4be71279f89bd18f82) to fix the bug in iOS 7. 
以后将加入更多的iOS 7 的测试以避免这种情况
